[package]
name = "ssh_forwarder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
russh = "0.54"
anyhow = "1"
clap = { version = "4.0", features = ["derive"] }